########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']

BASE_BOX_NAME = 'centos6point4'
BASE_BOX_URI = 'https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box'

Vagrant.configure('2') do |config|
  config.vm.define "agent_27_aws" do |agent_27_aws|
    #dummy box, will be overriden
    agent_27_aws.vm.box = "dummy"
    agent_27_aws.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    agent_27_aws.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      aws.ami = "ami-3b39ee4c"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "root"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant agent centos 27 build",
      }
        aws.security_groups = "vagrant_linux_build"
    end

    #need to sync folders
    agent_27_aws.vm.synced_folder "../../", "/cloudify-packager", create: true
    agent_27_aws.vm.provision "shell", path: "provision_py27.sh", privileged: false
  end

  config.vm.define :agent_27_vbox do |agent_27_vbox|
    agent_27_vbox.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    agent_27_vbox.vm.box = BASE_BOX_NAME
    agent_27_vbox.vm.box_url = BASE_BOX_URI
    agent_27_vbox.vm.hostname = 'local'
    agent_27_vbox.vm.synced_folder "../../", "/cloudify-packager", create: true
    agent_27_vbox.vm.provision "shell", path: "provision_py27.sh", privileged: false
  end

  config.vm.define "agent_26_aws" do |agent_26_aws|
    #dummy box, will be overriden
    agent_26_aws.vm.box = "dummy"
    agent_26_aws.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    agent_26_aws.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      aws.ami = "ami-3b39ee4c"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "root"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant agent centos 26 build",
      }
        aws.security_groups = "vagrant_linux_build"
    end

    #need to sync folders
    agent_26_aws.vm.synced_folder "../../", "/cloudify-packager", create: true
    agent_26_aws.vm.provision "shell", path: "provision_py26.sh", privileged: false
  end

  config.vm.define :agent_26_vbox do |agent_26_vbox|
    agent_26_vbox.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    agent_26_vbox.vm.box = BASE_BOX_NAME
    agent_26_vbox.vm.box_url = BASE_BOX_URI
    agent_26_vbox.vm.hostname = 'local'
    agent_26_vbox.vm.synced_folder "../../", "/cloudify-packager", create: true
    agent_26_vbox.vm.provision "shell", path: "provision_py26.sh", privileged: false
  end
end
